name: GNAT Linux
on:
  #schedule:
  #  - cron:  '0 0 * * *'
  #push:
  pull_request:


jobs:
  update:
    name: GNAT Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core

    - name: Install Ada dependencies
      run: sudo apt-get install gprbuild gnat

    - name: Build GNAT native
      run: ./anod build gcc -v --loglevel DEBUG

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: gcc-config-log
        path: sbx/x86_64-linux/gcc/build/config.log

    - name: Build GDB
      run: ./anod build gdb -v --loglevel DEBUG

    - name: Package GNAT
      run: ./anod build release_package --qualifier=package=gnat,do_gh_release -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - name: Build GNAT arm-elf
      run: ./anod build gcc -v --loglevel DEBUG --target=arm-elf

    - name: Build GDB arm-elf
      run: ./anod build gdb -v --loglevel DEBUG --target=arm-elf

    - name: Package GNAT arm-elf
      run: ./anod build release_package --qualifier=package=gnat,do_gh_release --target=arm-elf -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - name: Build GNAT riscv64-elf
      run: ./anod build gcc -v --loglevel DEBUG --target=riscv64-elf

    - name: Build GDB riscv64-elf
      run: ./anod build gdb -v --loglevel DEBUG --target=riscv64-elf

    - name: Package GNAT riscv64-elf
      run: ./anod build release_package --qualifier=package=gnat,do_gh_release --target=riscv64-elf -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool
      
    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: sbx/*/release_package*/install/*
